### ISSUE TITLE
Not able to add stackset outputs after initial deployment

### ISSUE THREAD

**Issue by hansarh** [aws-solutions/aws-control-tower-customizations#132]
**Describe the bug**
After I have deployed a stack_set and defined some `export_outputs` I am not able append additional outputs after the initial deployment. 
f.ex if I have defined a steck_set like this: 

``` Yaml
  - name: beta-sharing-public-subnets
    description: Sharing public subnets in networking hub account
    resource_file: network/templates/public-subnets-sharing.yaml
    parameter_file: network/parameters-prod/beta/public-subnets-sharing-parameters-beta.json
    deploy_method: stack_set
    export_outputs:
      - name: /public-subnet-eu-west-1a
        value: $[output_PublicSubnetIDAZA]
      - name: /public-subnet-eu-west-1b
        value: $[output_PublicSubnetIDAZB]
    deployment_targets:
      accounts:
        -  # networking-hub
    regions:
      - eu-west-1
```
Adding an output after this is deployed does not result in ana output being available for other stack_set definitions.
I might need to output a third subnet after some time like this:

``` Yaml
  - name: beta-sharing-public-subnets
    description: Sharing public subnets in networking hub account
    resource_file: network/templates/public-subnets-sharing.yaml
    parameter_file: network/parameters-prod/beta/public-subnets-sharing-parameters-beta.json
    deploy_method: stack_set
    export_outputs:
      - name: /public-subnet-eu-west-1a
        value: $[output_PublicSubnetIDAZA]
      - name: /public-subnet-eu-west-1b
        value: $[output_PublicSubnetIDAZB]
      - name: /public-subnet-eu-west-1b
         value: $[output_PublicSubnetIDAZC]
    deployment_targets:
      accounts:
        -  # networking-hub
    regions:
      - eu-west-1
```

**To Reproduce**
Try deploying a stack_set and append a new output after the initial deployment

**Expected behavior**
I expect adding an output to a stack_set will actually add an output.

**Please complete the following information about the solution:**
- [ x ] Version: v2.4.0 and v2.5.0

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0089) - customizations-for-aws-control-tower Solution. Version: v1.0.0_". You can also find the version from [releases](https://github.com/aws-solutions/aws-control-tower-customizations/releases)

- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
