### ISSUE TITLE
Incorrect parameter_value parsing when comma is present

### ISSUE THREAD

**Issue by lapkritinis** [aws-solutions/aws-control-tower-customizations#135]
**Describe the bug**
When deploying CFT if parameter is specified like this:
```
      - parameter_key: RoleType
        parameter_value: 'Standard (read only, custom policy)'
```
Parameter value gets modified to '`Standard (read only,custom policy)`' (space gets removed)

**To Reproduce**
Try launch template with such block:
```
Parameters:
  RoleType:
    Type: String
    AllowedValues:
      - Standard (read only, custom policy)
      - Standard-Managed (read only, AWS managed policy)
```

**Expected behavior**
It should pick specified value

**Please complete the following information about the solution:**
- [ ] Version: 2.5.1

**Comment by balltrev** [comment]
Thanks for bringing this to our attention @lapkritinis. This is actually a side effect it seems of the way we look for lists for `parameter_value`, I'll create a backlog with the team to discuss this.

**Comment by MykolaHorovykh** [comment]
Hello @balltrev Could you please share the solution to fix it?
Faced a similar issue with 
```
      - parameter_key: DefaultRoute
        parameter_value: 'RFC-1918 (10/8, 172.16/12, 192.168/16)'
```
The template is:
```
Parameters:
  DefaultRoute:
    Description: Default/Static route(s) to Transit Gateway - applicable to spoke account route table associated with the tagged subnets.
    Default: "All-Traffic (0/0)"
    Type: String
    AllowedValues:
      - "All-Traffic (0/0)"
      - "RFC-1918 (10/8, 172.16/12, 192.168/16)"
      - "Custom-Destinations"
      - "Configure-Manually"
```
The custom CustomControlTowerStackSetStateMachine parse this parameter value as 
```
        "DefaultRoute": [
          "RFC-1918 (10/8",
          "172.16/12",
          "192.168/16)"
        ]
```
Version: 2.8.1
