### ISSUE TITLE
Incorrect parsing parameter_value when value is set to Yes

### ISSUE THREAD

**Issue by lapkritinis** [aws-solutions/aws-control-tower-customizations#136]
**Describe the bug**
When deploying CFT if parameter is specified like this:
```
      - parameter_key: AssumeRoleRequired
        parameter_value: Yes 
```
Parameter value gets modified to '`true`' 

and stack fails to launch due allowed values constraint

**To Reproduce**
Try launch template with such block:
```
Parameters:
  AssumeRoleRequired:
    Type: String
    AllowedValues:
      - 'No'
      - 'Yes'
```

**Expected behavior**
It should pick specified value

**Please complete the following information about the solution:**
- [ ] Version: 2.5.1

**Comment by balltrev** [comment]
Hey @lapkritinis, I'm not actually able to reproduce this bug. Could you reach out to AWS Premium Support to help you with this issue?

**Comment by lapkritinis** [comment]
Testing if I can reopen it

**Comment by stumins** [comment]
Additional details from: https://github.com/aws-solutions/aws-control-tower-customizations/issues/140

To Reproduce
CFT. It works just fine if using AWS Console

```
AWSTemplateFormatVersion: "2010-09-09"
Description: Demo the issue with "Yes" with CCT

Parameters:
  Selection:
    Type: String
    AllowedValues:
      - 'No'
      - 'Yes'
    Default: 'No'

Conditions:
  SelectedYes: !Equals [ !Ref Selection, 'Yes' ]

Resources:
  S3Bucket:
    Condition: SelectedYes
    Type: AWS::S3::Bucket
```

Manifest part:

```
  - name: DemoIssue
    resource_file: templates/Test.yaml
    parameters:
      - parameter_key: Selection
        parameter_value: Yes
    deploy_method: stack_set
    deployment_targets:
      accounts:
        - security
```

Expected behavior
S3 bucket should be created

Instead I get error:

Parameter 'Selection' must be one of AllowedValues
