### ISSUE TITLE
Incorrect parsing parameter_value when value is set to Yes part 2

### ISSUE THREAD

**Issue by lapkritinis** [aws-solutions/aws-control-tower-customizations#140]
**Describe the bug**
I am setting up test case for issue #136 @balltrev 

**To Reproduce**
CFT. It works just fine if using AWS Console

```
AWSTemplateFormatVersion: "2010-09-09"
Description: Demo the issue with "Yes" with CCT

Parameters:
  Selection:
    Type: String
    AllowedValues:
      - 'No'
      - 'Yes'
    Default: 'No'

Conditions:
  SelectedYes: !Equals [ !Ref Selection, 'Yes' ]

Resources:
  S3Bucket:
    Condition: SelectedYes
    Type: AWS::S3::Bucket
```
Manifest part:

```
  - name: DemoIssue
    resource_file: templates/Test.yaml
    parameters:
      - parameter_key: Selection
        parameter_value: Yes
    deploy_method: stack_set
    deployment_targets:
      accounts:
        - security
```

**Expected behavior**
S3 bucket should be created

Instead I get error:

`Parameter 'Selection' must be one of AllowedValues`

**Please complete the following information about the solution:**
Version: [e.g. v1.5.1]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0089) - customizations-for-aws-control-tower Solution. Version: v1.0.0_". You can also find the version from [releases](https://github.com/aws-solutions/aws-control-tower-customizations/releases)

- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
