### ISSUE TITLE
Support for configurable Tags on Stack/StackSets on manifest file

### ISSUE THREAD

**Issue by nd-at-globetel** [aws-solutions/aws-control-tower-customizations#142]
When it comes to creation of StackSets in the CfCT manifest file, when there's an AWS Organization's SCP applied that prevents the creation of resources with non-compliant tagging (e.g. CloudFormation resources (Stack/StackSets). It's difficult to implement these compliant tags since we either need to reverse engineer the CfCT implementation and add the required tags on the source code of the CfCT itself or disable the SCP to allow the deployment of the Stacks/StackSets defined in the manifest file of the CfCT.

**Configurable Tags at the StackSet level**
A code snippet of the proposed feature request.

```
  - name: new-cool-stackset
    resource_file: templates/my-cool-stackset.yaml
    deploy_method: stack_set
    deployment_targets:
      organizational_units:
        - Sandbox
    # custom tagging implem here that will be applied to the my-cool-stackset stackset
    tags:
       - key: RequiredTagKey1
         value: RequiredTagValue1
       - key: RequiredTagKey2
         value: RequiredTagValue2

```

Thank you. AWS CfCT Team. I hope my feature request will be accommodated.
