### ISSUE TITLE
CfCT - error when enabling recommended controls 

### ISSUE THREAD

**Issue by RoxanaTeodosiu** [aws-solutions/aws-control-tower-customizations#167]
**Describe the bug**
When adapting the provided CfCT solution for enabling a recommended control from the CT list of controls, the CodePipeline fails at the "CloudformationResource" step with the following message: "ResourceLogicalId:RecommendedControlAWSGREC2VOLUMEINUSECHECK, ResourceType:AWS::ControlTower::EnabledControl, ResourceStatusReason:Resource handler returned message: "Organizational unit ou-xxxx-xxxxxxx is not registered with AWS Control Tower. (Service: AWSControlTower; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: xxxxxxxx; Proxy: null)" (RequestToken: xxxxxxxx, HandlerErrorCode: NotFound)." The error is found in the StackSet logs.

**To Reproduce**
Deploy the CfCT solution and create at least one OU with 2 accounts.
Modify the manifest file as following:
```
region: eu-west-1
version: 2021-03-15
enable_stack_set_deletion: true  
resources:
  - name: stackset-AWS-GR-EC2-VOLUME-INUSE-CHECK
    resource_file: example-configuration/templates/enable_controls.template
    deploy_method: stack_set
    deployment_targets: # accounts property is not supported for SCPs
      accounts: # :type: list
        - xxxxx
        - xxxxx
     regions:
      - eu-west-1
```

Add the referenced template file in example-configuration/templates/
```
AWSTemplateFormatVersion: '2010-09-09'
Description: Template for enabling controls in the Landing zone
Resources:
RecommendedControlAWSGREC2VOLUMEINUSECHECK:
        Type: "AWS::ControlTower::EnabledControl"
        Description: Detect whether Amazon EBS volumes are attached to Amazon EC2 instances
        Properties:
            ControlIdentifier: "arn:aws:controltower:eu-west-1::control/AWS-GR_EC2_VOLUME_INUSE_CHECK"
            TargetIdentifier: "arn:aws:organizations::xxxxxx:ou/o-yyyyy/ou-zzzz"
```

**Expected behavior**
The AWS-GR_EC2_VOLUME_INUSE_CHECK control should be enabled on the 2 accounts belonging to the existing and registered OU.

**Please complete the following information about the solution:**
- [ ] Version: latest version from git
- [ ] Region: [ eu-west-1]
- [ ] Were there any errors in the CloudWatch Logs? yes
Error from StackSets : "ResourceLogicalId:RecommendedControlAWSGREC2VOLUMEINUSECHECK, ResourceType:AWS::ControlTower::EnabledControl, ResourceStatusReason:Resource handler returned message: "Organizational unit ou-xxxx-xxxxxxx is not registered with AWS Control Tower. (Service: AWSControlTower; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: xxxxxxxx; Proxy: null)" (RequestToken: xxxxxxxx, HandlerErrorCode: NotFound)." 

**Additional context**
The CT, Ou and accounts have been deployed a week ago.
