### ISSUE TITLE
Allow deployment of AI Opt Out Policy and Declarative Policies

### ISSUE THREAD

**Issue by HeikoMR** [aws-solutions/aws-control-tower-customizations#210]
**Is your feature request related to a problem? Please describe.**
Hello,
we want to deploy AI Opt Out Policies via cfct. Right now that is only possible for scps and rcps.
Also same for declarative policies.

**Describe the feature you'd like**
Please add the possibility to deploy ai opt out policies via cfct

Example reference in manifest:
```  
   # ai opt out policy to prevent public SQS Policy
   - name: ai-opt-out-policy
    description: Custom ai opt out policy to deny data usage from aws for ai improvements
    resource_file: policies/ai-opt-out-policy.json
    deploy_method: aioop
    deployment_targets: 
      organizational_units:
        - Root
```

**Additional context**
https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_ai-opt-out.html

Thanks in advance
Heiko
