### ISSUE TITLE
Stack Set fails after accounts became suspended

### ISSUE THREAD

**Issue by hitty5** [aws-solutions/aws-control-tower-customizations#86]
**Describe the bug**
Stack set operations fails due to terminated / suspended accounts.

**To Reproduce**
Assuming following organization:

```
Root
- DEV
-- Account 1 (governed with control tower)
```
Following manifest:

```
---
region: eu-central-1
version: 2021-03-15

resources:
  - name: rules
    deploy_method: stack_set
    resource_file: templates/rules.template
    deployment_targets:
      organizational_units:
        - DEV
    regions:
      - eu-central-1
```
Now the account 'Account 1' gets terminated, meaning the accounts is removed from control tower (=the corresponding provisioned product get deleted). This action moves the account from the origin OU to the root OU. Furthermore the role 'AWSControlTowerStackSetRole' get removed from the account as well, so the stack set cannot perform any operation anymore, which lets the stack set fail.

**Expected behavior**
The stack set detects the movement and removes the corresponding stack instance, like it would be with auto-deployment mode.

**Please complete the following information about the solution:**
- [ ] Version 2.1.0
- [ ] Region: eu-central-1
- [ ] Was the solution modified from the version published on this repository? NO
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? YES
- [ ] Were there any errors in the CloudWatch Logs? NO
